title: Aprendizaje automático
url: "https://ankitsultana.com"
baseurl: ""
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ucvia"
footer_text: "UCVIA | ML | Template basado en Research de Anki Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Principal"
   link: "/"
 - name: "Nota informativa"
   link: "AprendizajeAutomatico-6561.pdf"
 - name: "Contacto"
   link: "contacto"
